os: linux
language: haskell

cabal: "2.4"
ghc: "8.6.5"

cache:
  directories:
  - "$HOME/.cabal/store"

install:
- cabal v2-update

script:
- cabal v2-configure --enable-tests --enable-benchmarks -v2
- cabal v2-build

notifications:
  slack:
    secure: qfdrwXtzre9ulMph2Tw4mQbRQSR84KneKSvIF/qDjJYvVtrGSa92t06gUCcga15jsMfyiUltjqfOeU7LwJdp9k56HpYMU9qXCWjaSL9GR/h99Z/nEyXsFTHsD/fkUWNcGiKlib2kRjeI30wQMG/0ttYDl/s81WsUFPgR5ToFQCQgxhv1WswWuZxZ1M1NI4rf5UzVYAXNoLlh1XijGmlF/j/IHGuCXf1RWg/IR+ZKfaesmY7Kmmh9OcBM7eNlfaslYuWPxACPU421qqPWFxmMZVKwc+OcktzlDkT+I7D06lxFWwq+kzJi9w4Ab+caPT0UKld1bCYfctDwi5yy5wB54435OMcRS7Qd3tCCqE/n/Pb0TzrgmuIVWCzmDxCjwytzQulWgIOcuG4djoHblJoVL+n1zItdzNpoHAIhKRuo4tI4tLghGCLgMu2GqL6UyQkx11V6wvKx+NlRqP4HXN2D/IEZnYjpPvZvc5BSYFGZQS5zwdaY7X3YwLp3oueTM7ijLxb+CCexLVz9Ug43RCD4EhTag7s5s42qzblV8wnq1huEbmmZb6irP77vZsO9FBdFOaM5ucUo+P0W3Eb9QWrpa+XM2S2nTUWR6WDITYzpMcrlD6osdlOrgf3HBxjOffo9iHXR8u+5k1StWyvTKH0CYpzeGMWTWs0WerISmtBEa3k=
