# Inspired by Cabal's appveyor.yml:
# https://github.com/ghc/packages-Cabal/blob/master/appveyor.yml

# '-y', 'refreshenv' and 'echo "" |' are workarounds

install:
  - choco install -y cabal --version 2.4.1.0
  - choco install -y ghc --version 8.6.5
  - refreshenv
  - cabal v2-update

build_script:
  - echo "" | cabal v2-configure --enable-tests --enable-benchmarks -v2
  - echo "" | cabal v2-build
