# Inspired by Cabal's appveyor.yml:
# https://github.com/ghc/packages-Cabal/blob/master/appveyor.yml

# '-y', 'refreshenv' and 'echo "" |' are workarounds

install:
  - choco install -y ghc --version 8.0.1 > NUL
  - refreshenv
  - curl -o cabal.zip --silent https://www.haskell.org/cabal/release/cabal-install-1.24.0.0/cabal-install-1.24.0.0-x86_64-unknown-mingw32.zip
  - 7z x -bd cabal.zip
  - cabal --version
  - cabal update

build_script:
  - echo "" | cabal install --only-dependencies --enable-tests --enable-benchmarks
  - echo "" | cabal configure --enable-tests --enable-benchmarks -v2
  - echo "" | cabal build
