-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.1"

ideasRevision :: Int
ideasRevision = 5787

ideasLastChanged :: String
ideasLastChanged = "za, 08 jun 2013"
