-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.2"

ideasRevision :: Int
ideasRevision = 6098

ideasLastChanged :: String
ideasLastChanged = "di, 10 dec 2013"
