-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.3"

ideasRevision :: Int
ideasRevision = 7519

ideasLastChanged :: String
ideasLastChanged = "wo, 08 apr 2015"
